#!/bin/bash

defaultNameserver="8.8.8.8"

timezone="Europe/Istanbul"

DESTINATION=/mnt/gentoo

KERNEL_SOURCES="sys-kernel/gentoo-sources"

parted -a optimal /dev/sda << END

parted /dev/sda --script mklabel gpt
parted /dev/sda --script unit mib
parted /dev/sda --script mkpart primary 1 3
parted /dev/sda --script name 1 grub
parted /dev/sda --script set 1 bios_grub on
parted /dev/sda --script mkpart primary 3 131
parted /dev/sda --script name 2 boot
parted /dev/sda --script mkpart primary 131 643
parted /dev/sda --script name 3 swap
parted /dev/sda --script mkpart primary 643 -- -1
parted /dev/sda --script name 4 rootfs
parted /dev/sda --script set 2 boot on
END
mkfs.ext2 /dev/sda2
mkfs.ext4 /dev/sda4

mkswap /dev/sda3
swapon /dev/sda3

mount /dev/sda4 /mnt/gentoo

ntpd -q -g

cd /mnt/gentoo
wget distfiles.gentoo.org/releases/amd64/autobuilds/20190929T214502Z/stage3-amd64-20190929T214502Z.tar.xz
tar xpvf stage3-*.tar.xz --xattrs-include='*.*' --numeric-owner

echo MAKEOPTS='"-j3"' >> /mnt/gentoo/etc/portage/make.conf

mirrorselect -i -c 'Turkey' >> /mnt/gentoo/etc/portage/make.conf

mkdir --parents /mnt/gentoo/etc/portage/repos.conf
cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/gentoo.conf

cp --dereference /etc/resolv.conf /mnt/gentoo/etc/

mount --types proc /proc /mnt/gentoo/proc
sleep 2s
mount --rbind /sys /mnt/gentoo/sys
sleep 2s
mount --make-rslave /mnt/gentoo/sys
sleep 2s
mount --rbind /dev /mnt/gentoo/dev
sleep 2s
mount --make-rslave /mnt/gentoo/dev
sleep 2s
chroot /mnt/gentoo /bin/bash << END
source /etc/profile
export PS1="(chroot) ${PS1}"
#!/bin/bash

mount dev/sda2 /boot

emerge-webrsync
eselect news read
eselect profile set default/linux/amd64/17.0

emerge --verbose --update --deep --newuse @world
sleep 2s
emerge --config sys-libs/timezone-data

echo "en_US ISO-8859-1" >> /etc/locale.gen
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen

env-update && source /etc/profile && export PS1="(chroot) ${PS1}"


emerge sys-kernel/gentoo-sources
echo "sys-apps/util-linux static-libs" >> /etc/portage/package.use/custom
mkdir /etc/portage/package.license
echo "sys-kernel/linux-firmware linux-fw-redistributable no-source-code" >> /etc/portage/package.license/customd ..

emerge sys-kernel/genkernel
echo "/dev/sda2     /boot	ext2    defaults, noatime    0 2" >> /etc/fstab
echo "/dev/sda3     none        swap    sw                   0 0" >> /etc/fstab
echo "/dev/sda4     /           ext4    noatime              0 1" >> /etc/fstab
echo "/dev/cdrom    /mnt/cdrom  auto    noauto, user         0 0" >> /etc/fstab
genkernel all
echo 'hostname="edacicekli"' > /etc/conf.d/hostname
echo '127.0.0.1    edacicekli.online edacicekli localhost' > /etc/hosts
echo '::1    localhost' >> /etc/hosts
echo "root:edaa1997" | chpasswd

emerge app-admin/sysklogd
rc-update add sysklogd default

emerge --verbose sys-boot/grub:2
grub-install /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
exit
END


umount -l /mnt/gentoo/dev{/shm,/pts,}
umount -R /mnt/gentoo
reboot
